version: '2'

services:
  akeneo:
    image: carcel/akeneo:php-5.6
    depends_on:
      - mysql
      - mongodb
    environment:
      PHP_XDEBUG_ENABLED: 0
      XDEBUG_CONFIG: remote_host=10.254.254.254
      PHP_IDE_CONFIG: "serverName=phpstorm_localhost"
      PHP_XDEBUG_IDE_KEY: PHPSTORM
      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254
    ports:
      - 'akeneo_port:80'
    volumes:
      - /paths:/home/docker/pim
      - /composer_path:/home/docker/.composer
    working_dir: /home/docker/pim
    networks:
      - akeneo

  akeneo-behat:
    image: carcel/akeneo-behat:php-5.6
    depends_on:
      - mysql-behat
      - mongodb-behat
      - selenium
    environment:
      BEHAT_TMPDIR: /home/docker/pim/app/cache/tmp
      PHP_XDEBUG_ENABLED: 0
      XDEBUG_CONFIG: remote_host=10.254.254.254
      PHP_IDE_CONFIG: "serverName=phpstorm_localhost_behat"
      PHP_XDEBUG_IDE_KEY: PHPSTORM
      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254
    ports:
      - 'akeneo_behat_port:80'
    volumes:
      - /paths:/home/docker/pim
      - /composer_path:/home/docker/.composer
      - /behat_screenshots:/tmp/behat/screenshots
    working_dir: /home/docker/pim
    networks:
      - behat

  selenium:
    image: selenium/standalone-firefox-debug:2.53.1-beryllium
    ports:
      - 'akeneo_selenium_port:5900'
    volumes:
      - /paths:/home/docker/pim
    networks:
      - behat

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=akeneo_pim
      - MYSQL_PASSWORD=akeneo_pim
      - MYSQL_DATABASE=akeneo_pim
    networks:
      - akeneo

  mysql-behat:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=akeneo_pim
      - MYSQL_PASSWORD=akeneo_pim
      - MYSQL_DATABASE=akeneo_pim
    networks:
      - behat

  mongodb:
    image: mongo:2.6
    networks:
      - akeneo

  mongodb-behat:
    image: mongo:2.6
    networks:
      - behat

networks:
  akeneo: ~
  behat: ~
